"""
    EulerBeam3DwithStrainGauge

An element designed to wrap around an EulerBeam3D. The element makes no contribution 
to residual or Lagrangian besides the contribution made by the element it wraps.
`EulerBeam3DwithStrainGauge` provides requestables allowing to model strain gauges. The
strain gauges are placed halfway along the `EulerBeam3D`. In an inverse analysis, the
`EulerBeam3DwithStrainGauge` is itself wraped by an `ElementCost` element.

# Keyword arguments when adding elements:

- `P` `SMatrix{3,Nsensor,𝕣}`, giving the offset between the point on the axis of the 
   element halfway along its length. `P[1,:]` must be zero.
- `D` `SMatrix{3,Nsensor,𝕣}`, the orientation of a strain gauge. If multiple strain gauges 
   are present at the same position, one can repeat the columns of `P`.
- `ElementType=EulerBeam3D` the constructor to the wrapped element.  This is typicaly
   an `EulerBeam3D` but could be another element wrapping an `EulerBeam3D`.
- `elementkwargs` a `NamedTuple` with the keyword arguments to the wrapped element.  See [`EulerBeam3D`](@ref)   

# Requestables:

- `εₐₓ` (scalar), the axial strain at the middle of the element
- `κ` a vector with elements: 
        `κ[1]` the torsion at the middle of the element.
        `κ[2]` the component of te curvature in `EulerBeam3D`'s direction 2.
        `κ[3]` the component of te curvature in `EulerBeam3D`'s direction 3.
    Although a tri-vector that includes torsion may erroneously suggest 
    a rotation rate vector, the `κ[2:3]` points to the inside of the curvature    
    and the unit is in `1/L` (not `rad/L`) where `L` is the unit of length of
    the model.
- `ε` a vector of length `Nsensor` containing the strain values defined by `P`
   and `D`.    

#Keyword arguments when drawing elements:

When calling `draw!`, instruction to `EulerBeam3DwithStrainGauge` elements are given as in this example:

    draw!(axis,state>;EulerBeam3DwithStrainGauge=(L= @SVector [0.1,0,0],point_size=10,accelerometer_color=:orange))`

The optional keword arguments and their default values are  
- `gauge_color = :blue`
- `expand      = 1.02` a multiplicative factor applied to `P` in the drawing only (not in strain calculation)
   to ensure the gauge is not hidden by a patch-drawing of the beam itself.
- `L           = SVector{Nsensor,𝕣}(norm(P)/5 for i=1:Nsensor)` the length of the strain gauge in the drawing  TODO

    
"""
struct EulerBeam3DwithStrainGauge{Ngauge,Teleobj,Treq} <: AbstractElement
    eleobj   :: Teleobj
    req      :: Treq
    P        :: SMatrix{3,Ngauge,𝕣}  # P[1] must be zero
    D        :: SMatrix{3,Ngauge,𝕣}
    E        :: SVector{  Ngauge,𝕣} 
    K1       :: SVector{  Ngauge,𝕣}  
    K2       :: SVector{  Ngauge,𝕣}  
    K3       :: SVector{  Ngauge,𝕣}  
end
function EulerBeam3DwithStrainGauge(nod::Vector{Node};P,D,ElementType=EulerBeam3D,elementkwargs)  # Teleobj because we may wrap wrapped beams
    req       = @request (ε,κ)
    eleobj    = ElementType(nod;elementkwargs...)
    all(P[1,:].==0.) || muscadeerror("In arguments of EulerBeam3DwithStrainGauge, P[1,:] must all be zero")
    E         =  D[1,:].^2
    K1        =  D[1,:].*(D[3,:].*P[2,:].-D[2,:].*P[3,:])  
    K2        = -D[1,:].^2 .*P[2,:]
    K3        = -D[1,:].^2 .*P[3,:]
    return EulerBeam3DwithStrainGauge(eleobj,(strain=req,),P,D,E,K1,K2,K3)
end
Muscade.no_second_order(::Type{<:EulerBeam3DwithStrainGauge{Ngauge,Teleobj}}) where{Ngauge,Teleobj} = Muscade.no_second_order(Teleobj)
Muscade.doflist( ::Type{<:EulerBeam3DwithStrainGauge{Ngauge,Teleobj}}) where{Ngauge,Teleobj} = Muscade.doflist(Teleobj)
@espy function Muscade.residual(o::EulerBeam3DwithStrainGauge, X,U,A,t,SP,dbg)
    req          = mergerequest(o.req) # @espy will generate req = merge(o.req,req) where req is the additional argument of lagrangian method generated by espy
    R,FB,☼eleres = Muscade.getresidual(o.eleobj,X,U,A,t,SP,(dbg...,via=EulerBeam3DwithStrainGauge),req.strain) 
    ☼εₐₓ,☼κ      = ∂0(eleres.ε), ∂0(eleres.κ)   
    ☼ε           = o.E*εₐₓ .+ o.K1*κ[1] .+o.K2*κ[2] .+ o.K3*κ[3] 
    return R,FB
end   
function Muscade.allocate_drawing(axis,o::AbstractVector{Gauge};kwargs...) where{Gauge<:EulerBeam3DwithStrainGauge{Ngauge}} where{Ngauge}  
    mutt,optt    = Muscade.allocate_drawing(axis,[oᵢ.eleobj for oᵢ∈o];kwargs...)
    args         = default{:EulerBeam3DwithStrainGauge}(kwargs,(;)     ) 
    opt          = default(args,(gauge_color=:lightgreen,expand=1.02,target=optt,L=1.))
    nel          = length(o)
    x            = 𝕣2(undef,3,3*Ngauge*nel)       # 3D, end1-end2-nan, ngauge, nel
    rx           = reshape(x,3,3,Ngauge,nel)
    rx[:,3,:,:] .= NaN
    mut          = (target=mutt, gauge=x)
    
    return mut,opt
end
function Muscade.update_drawing(  axis,o::AbstractVector{Gauge},oldmut,opt, Λ,X,U,A,t,SP,dbg) where{Gauge<:EulerBeam3DwithStrainGauge{Ngauge}} where{Ngauge} 
    X₀                   = ∂0(X)
    nel                  = length(o)
    rx                   = reshape(oldmut.gauge,3,3,Ngauge,nel)
    for (iel,oᵢ) ∈ enumerate(o)
        gp,ε,vₛₘ,rₛₘ,vₗ₂,uₗ₂,cₛₘ = kinematics{:direct}(oᵢ.eleobj,view(X₀,:,iel))
        rx[:,1,:,iel]    = rₛₘ ∘₁ (oᵢ.P*opt.expand .+ opt.L*oᵢ.D) .+ cₛₘ
        rx[:,2,:,iel]    = rₛₘ ∘₁ (oᵢ.P*opt.expand .- opt.L*oᵢ.D) .+ cₛₘ
    end
    mutt = Muscade.update_drawing(  axis,[eᵢ.eleobj for eᵢ∈o],oldmut.target,opt.target, Λ,X,U,A,t,SP,dbg) 
    mut  = (target=mutt,gauge = oldmut.gauge )
    return mut
end
function Muscade.display_drawing!(axis,::Type{<:EulerBeam3DwithStrainGauge{Ngauge,Teleobj}},obs,opt) where{Ngauge,Teleobj}                         
    lines!(axis,obs.gauge,color = opt.gauge_color ,linewidth=3)
    Muscade.display_drawing!(axis,Teleobj,obs.target,opt.target)
end
